### ISSUE TITLE
Display too small on screen in 3000*2000 in 13inch

### ISSUE THREAD

**Issue by LotuxPunk** [prmr/JetUML#233]
Hello, 
I have a Surface Book, and my screen has a large resolution on a 13-inch screen, so the different elements in the interface look small. An option to adjust that? 

![image](https://user-images.githubusercontent.com/16562647/36017652-ed7eba82-0d78-11e8-830d-af24e67cafc6.png)

![2018-02-09](https://user-images.githubusercontent.com/16562647/36017920-fc6963fc-0d79-11e8-8f05-daeb57677924.png)

**Comment by prmr** [comment]
This is a know issue caused by the fact that the current GUI library used (Swing) does not support HD screens. We are actively working on this with a port to JavaFX (#232 ), which will go into Release 2.0, scheduled for the Spring. In the meantime, two workarounds include:
* Using the Zoom feature (`View | Zoom In`) which at least makes the diagrams easier to see.
* (For the more adventurous) check out branch `Integration-JavaFX`, which already has the outer frame and dialogs ported, and will progressively become more HD-Screen friendly over the next few week.
