### ISSUE TITLE
Make connections/edges smarter

### ISSUE THREAD

**Issue by johannesrave** [prmr/JetUML#375]
**Description**
When more than a few edges are on screen, they interfere with each other and make the diagram hard to read graphically. I spend considerable time repositioning the nodes, just to avoid this. When deciding on an overall layout of a diagram, I think the edge obstructions shouldn't be this much of a concern.

**Steps to reproduce**
1. Draw a diagram with lots of inheritance or composition from more than one source node.
2. Look at it.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/31467653/91308965-53897880-e7b0-11ea-96f8-2894a2355115.png)

**Configuration**
 - JetUML Release: 3.0
 - OS + version: Windows 10
 - Java version openjdk version "13.0.2"
 
**Additional information**
I am taking my first steps toward learning JavaFX in my CS degree, so maybe I could tackle this. I haven't yet contributed to OSS yet though, so would need an introduction, but I am looking for a project to contribute to.

**Comment by prmr** [comment]
Related to #230. However, the latter is the refactoring required to enable the edge layout improvement. There is definitely a plan to improve the edge layout, but making this layout editable is out of scope as it takes away from the minimalist vision for the tool.

**Comment by johannesrave** [comment]
I absolutely see your point about the scope of JetUML, and expected this perspective. It'd be nice to still enable my usecase of having medium-sized diagrams with a certain amount of edges with robust automatic placement, so I'm glad work in this direction is planned.

**Comment by prmr** [comment]
## Design sketch:
1. Provide an _edge category_ scheme in terms of their visual appearance. For example, implementation edges, extension edges, composition edges, etc.
2. Establish a _priority_ scheme so that edges in one category get drawn first (so that it's possible to take their layout into account when drawing other edges). For examples, extension edges go first, then implementation edges, etc.
3. Establish a fix scheme for attaching edges to nodes based on their category. For example, extension edges always attach to the center of a node's side, then immediately after come the implementation edges, etc.
4. The edge's attachment to the node should take into account its position relative to the node, so we avoid edge crossings.
5. This will require to move away from the pure-stateless edge drawing algorithm, since edge layouts will need to be remembered between categories. We will this have a system based on passes through the edges.

**Comment by johannesrave** [comment]
This looks very good.
However, the problems I had also stemmed from edges crossing nodes, as in my original screenshot - maybe there is a way to incorporate their position and extend into the "pathfinding" as well?
