### ISSUE TITLE
Empty Property Editor

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#44]
In the framework, it is possible to bring up a properties editor even for an object that has no properties. For example, an note edge. This should not happen: if the object has no property, the behavior should default to do nothing.

**Comment by JoelChev** [comment]
I just commited a fix for this; please check it out when you get the chance. I can modify this if necessary. I wasn't paying attention however and Issue0044 (Branch #44) was accidentally created as a new branch from Issue0047+0054  (Bracnh #47 and #54), instead of from the master branch. Consequently the state diagram fixes are in Issue0044 as well. I will be more careful going forward, but I figure it shouldn't be a big deal here as all these issues are not very large in scope. Thanks!
