### ISSUE TITLE
Small visual glitch with aggregation line in class diagram

### ISSUE THREAD

**Issue by cjoudrey** [prmr/JetUML#474]
**Description**

I was in the process of drawing a class diagram with two arrows pointing between two objects and noticed a slight visual glitch.

It's not a big deal, but I figured I'd open an issue in case it is a low hanging fruit.

**Screenshots**

Notice how the aggregate line isn't fully straight:

<img width="614" alt="Screen Shot 2022-10-19 at 1 55 14 PM" src="https://user-images.githubusercontent.com/385270/196768065-8572f368-613f-4ca4-9059-07ab2ad2c0a7.png">

**Configuration**
 - JetUML Release: 3.4
 - OS + version: macOS 12.6
 - Java version: 17.0.4.1

**Comment by prmr** [comment]
The root cause is the specification of the behavior of `NodeIndex#toPoint`, which computes attachment points on a node face attempting to maximize the space available on the space of the node. As observed, the excess precision can lead to a suboptimal look.

I will change the function so that the output is more visually pleasing.
