### ISSUE TITLE
Feature for underlining and italics?

### ISSUE THREAD

**Issue by enes-yumer-vinci** [prmr/JetUML#512]
Hi, I have been using JetUML for my studies. However, I need to underline text and the feature isn't available. Would it be possible to add it? 

Thank you

**Comment by prmr** [comment]
Currently looking into it.

**Comment by jkcoding7** [comment]
Users can now **underline** and **italicize** their static and abstract elements, respectively, using markups.

- Underline markup: Surround the desired element with underscores. This is only allowed for class attributes and methods.
E.g.  \_getArea(): double\_
- Italics markup: Surround the desired element with forward slashes. This is only allowed for class names and methods.
E.g.  /Shape/

Notes: 
1. _Any_ leading or trailing spaces before or after the markups will result in the markup not being applied. 
2. A combination of underlining and italicizing is not supported since an element cannot be both static and abstract. More precisely,
/_ XXX _/ would make the element abstract and
\_/ XXX /\_ would make it underlined.
Only the outside decoration would be applied.
