### ISSUE TITLE
Broken tests in master branch

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#63]
A change to the persistence format broke the tests for `PersistenceService`.

**Comment by EJBQ** [comment]
These two commits should fix changes in persistence testing from what @JoelChev did with the node sizes. 

Reading and writing graphs appears to have been broken by the immutability of ClassRelationshipEdge, because the XMLDecoder was using the public methods to edit edges when reading them in. When trying to save it seems to be failing because of the BeanInfo change though. So I am working on those two things right now, to see if there is a workaround from having those methods public.

**Comment by EJBQ** [comment]
Also of note: When saving the graph in the object diagram test, it switches the order of the fields of the empty middle object, so it goes 4-3-2, not 2-3-4.

**Comment by EJBQ** [comment]
This commit takes away the in-code immutability of the edges which was breaking the saving and loading JavaBeans code, but keeps it immutable from the user perspective and keeps the creation in static methods.

Now all persistence tests work except the object diagram, which I and Joel are looking at.

**Comment by EJBQ** [comment]
So I've been talking with Joel. The object test works for him but fails on both my computers, even after restarting and recloning. @prmr, can you try the TestPersistenceService on your machine in the 63b branch?

**Comment by prmr** [comment]
Works for me.

**Comment by EJBQ** [comment]
Then I believe it's all working, and should be ready to merge in so we can move along. There must be something wrong with my installation or something.
