### ISSUE TITLE
Select Element After Creation

### ISSUE THREAD

**Issue by prmr** [prmr/JetUML#64]
Currently when you want to create a model element and name it (e.g., a class), you have to create it, select the selection tool, select it, then click the name field. I have a tendency to try to do this which results in the annoying behavior that multiple classes get created. Instead, if a selection tool is active but the mouse is clicked inside an object that cannot be the parent of the created element, the object clicked should be selected and it's property editor opened instead.

**Comment by prmr** [comment]
The focus part is handled in #69

**Comment by JoelChev** [comment]
I have added logic now so that if you click on a Node, it will switch the tool to be the Selection tool instead. There are currently three exceptions to this rule: PackageNodes, ObjectNodes and ImplicitParameterNodes (as these nodes can contain other nodes inside them). Now, when a user clicks on a node twice, it will display its property editor for them, with the first field selected.
