### ISSUE TITLE
Duplication of Call Nodes

### ISSUE THREAD

**Issue by EJBQ** [prmr/JetUML#72]
Steps to reproduce:
1) Create a Sequence Diagram
2) Create two ImplicitParameterNodes with one CallNode each
3) Make an edge from the left CallNode to the right one
4) Copy and Paste this entire setup

Expected output: An exact copy of what was copied
Actual Output: A second child of the CallNode without an edge to it. You may need to move the pasted parent call node to see the duplicated node.

**Comment by EJBQ** [comment]
The seemingly related issue of deleting and undoing a child call node duplicating the child seems to have been created in the Issue0062 branch, with the addition of edge lists in nodes. Removing that merge gets rid of that part of the issue. @JoelChev , can you look into this issue some?

**Comment by JoelChev** [comment]
Hey, thanks for finding this Eric. I will look into it tomorrow evening or on Wednesday once I finish with my final exams. I will keep you and @prmr posted.

**Comment by prmr** [comment]
Any movement on this?

It seems the problem is caused by the last `for` loop in `Clipboard.pasteInto(GraphPanel pGraphPanel, boolean pOriginalPositions)`. This makes a call to `Graph.connect`, and inside this call one call node is not found, and re-created. Besides the bug, this implementation appears to be inconsistent with the Javadoc of the method connect, which says that if both nodes are not found, the edge is not added. This needs to be inspected more carefully.

**Comment by JoelChev** [comment]
The bug seems to be resolved on my end. I just added a small if statement to skip the Graph.connect step on CallNode->CallNode edges. This seems to do the trick, although it doesn't actually solve whatever the underlying problem is. I've also refactored the Clipboard class to comply with the Checkstyle guidelines. Everything should be good to go for Milestone 1.0 now.
